//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class ProfileInfo
{
    public int ProfileId { get; set; }
    public string ImageName { get; set; }
    public string ImageType { get; set; }
    public System.Guid ImageGuid { get; set; }
    public Nullable<int> UserId { get; set; }
}
